variable "project_id" {
  description = "Project the VPC is created in."
  type        = string
}

variable "name" {
  description = "VPC name (generated by the naming layer: vpc-<key>-<code>-gbl0)."
  type        = string
}

variable "description" {
  description = "VPC description."
  type        = string
  default     = ""
}

variable "auto_create_subnetworks" {
  description = "Auto-mode subnet creation. The framework is custom-mode only (subnets are config documents); the config schema does not even expose this — module input exists for completeness."
  type        = bool
  default     = false
}

variable "routing_mode" {
  description = "Dynamic routing mode."
  type        = string
  default     = "GLOBAL"

  validation {
    condition     = contains(["GLOBAL", "REGIONAL"], var.routing_mode)
    error_message = "routing_mode must be GLOBAL or REGIONAL."
  }
}

variable "mtu" {
  description = "Network MTU (null = provider default 1460). Jumbo 8896 for NSI/inspection VPCs — note the DHCP cold-cycle platform quirk when changing MTU on running instances."
  type        = number
  default     = null

  validation {
    condition     = var.mtu == null || try(var.mtu >= 1300 && var.mtu <= 8896, false)
    error_message = "mtu must be between 1300 and 8896 (or null for provider default)."
  }
}

variable "delete_default_internet_gateway_routes" {
  description = "Delete the auto-created 0.0.0.0/0 internet routes on create. Required true on VPCs that must learn their default from an NVA/hybrid path — a local 0/0 suppresses the learned one (see design_and_backlog/2-tier-ncc-2region-nsi.md)."
  type        = bool
  default     = false
}

variable "enable_ula_internal_ipv6" {
  description = "Enable ULA internal IPv6 on this network."
  type        = bool
  default     = false
}

variable "internal_ipv6_range" {
  description = "Explicit ULA range (when enable_ula_internal_ipv6); null = auto-assigned."
  type        = string
  default     = null

  validation {
    condition     = var.internal_ipv6_range == null || var.enable_ula_internal_ipv6
    error_message = "internal_ipv6_range requires enable_ula_internal_ipv6 = true (API rejects it otherwise)."
  }
}

variable "firewall_policy_enforcement_order" {
  description = "Network firewall policy evaluation order. BEFORE_CLASSIC_FIREWALL required on NSI consumer VPCs (see design_and_backlog/2-tier-ncc-2region-nsi.md); null = provider default (AFTER_CLASSIC_FIREWALL)."
  type        = string
  default     = null

  validation {
    condition     = var.firewall_policy_enforcement_order == null || contains(["AFTER_CLASSIC_FIREWALL", "BEFORE_CLASSIC_FIREWALL"], coalesce(var.firewall_policy_enforcement_order, "AFTER_CLASSIC_FIREWALL"))
    error_message = "firewall_policy_enforcement_order must be AFTER_CLASSIC_FIREWALL or BEFORE_CLASSIC_FIREWALL (or null)."
  }
}

variable "bgp_best_path_selection_mode" {
  description = "Network-level BGP best-path algorithm: LEGACY | STANDARD (null = provider default LEGACY). STANDARD unlocks the MED/inter-region knobs that route preference across redundant hybrid paths depends on."
  type        = string
  default     = null

  validation {
    condition     = var.bgp_best_path_selection_mode == null || contains(["LEGACY", "STANDARD"], coalesce(var.bgp_best_path_selection_mode, "x"))
    error_message = "bgp_best_path_selection_mode must be LEGACY or STANDARD."
  }
}

variable "bgp_always_compare_med" {
  description = "Compare MED across routes from DIFFERENT neighbor ASNs — STANDARD mode only (API constraint)."
  type        = bool
  default     = null

  validation {
    condition     = var.bgp_always_compare_med == null || coalesce(var.bgp_best_path_selection_mode, "LEGACY") == "STANDARD"
    error_message = "bgp_always_compare_med requires bgp_best_path_selection_mode = STANDARD."
  }
}

variable "bgp_inter_region_cost" {
  description = "Inter-region cost behavior in best-path selection: DEFAULT | ADD_COST_TO_MED — STANDARD mode only."
  type        = string
  default     = null

  validation {
    condition     = var.bgp_inter_region_cost == null || (contains(["DEFAULT", "ADD_COST_TO_MED"], coalesce(var.bgp_inter_region_cost, "x")) && coalesce(var.bgp_best_path_selection_mode, "LEGACY") == "STANDARD")
    error_message = "bgp_inter_region_cost must be DEFAULT or ADD_COST_TO_MED, and requires STANDARD mode."
  }
}
