variable "project_id" {
  description = "Project the hub is created in (stage-0 membership: container ID only, no VPC references)."
  type        = string
}

variable "name" {
  description = "Hub name (generated by the naming layer: hub-<key>-<code>-gbl0)."
  type        = string
}

variable "description" {
  description = "Hub description."
  type        = string
  default     = ""
}

variable "topology" {
  description = "Hub preset topology. hybrid_inspection is the NSI-oriented preset (enum verified present in provider google 7.41.0; older 7.x may reject it at plan)."
  type        = string
  default     = "mesh"

  validation {
    condition     = contains(["mesh", "star", "hybrid_inspection"], var.topology)
    error_message = "topology must be mesh, star, or hybrid_inspection."
  }
}

variable "export_psc_routes" {
  description = "Export Private Service Connect routes across the hub."
  type        = bool
  default     = false
}

variable "auto_accept" {
  description = "Auto-accept project lists keyed by REAL GROUP NAME (`mesh` is a topology name, not a group; the mesh group is literally `default`). map because `non-prod` is not a legal object attribute. Omitted group = review-everything for that group."
  type        = map(list(string))
  default     = {}

  validation {
    condition = alltrue([
      for g in keys(var.auto_accept) : contains(
        var.topology == "mesh" ? ["default"] :
        var.topology == "star" ? ["center", "edge"] :
      ["gateways", "prod", "non-prod", "services"], g)
    ])
    error_message = "auto_accept keys must be the topology's REAL group names: mesh->default; star->center/edge; hybrid_inspection->gateways/prod/non-prod/services (the preset pre-seeds autoAccept; user amendments are accepted - verified on a live apply)."
  }
}

variable "labels" {
  description = "Labels applied to the hub."
  type        = map(string)
  default     = {}
}
