variable "type" {
  description = "Policy flavor: hierarchical (org/folder) | global | regional network policy."
  type        = string

  validation {
    condition     = contains(["hierarchical", "global", "regional"], var.type)
    error_message = "type must be hierarchical, global, or regional."
  }
}

variable "name" {
  description = "Policy name / short_name (generated by the naming layer: fp-<function>-<code>-<scope>)."
  type        = string
}

variable "description" {
  description = "Policy description."
  type        = string
  default     = ""
}

variable "project_id" {
  description = "global/regional only: project the policy is created in."
  type        = string
  default     = null
}

variable "region" {
  description = "regional only: long-form region."
  type        = string
  default     = null

  validation {
    condition     = (var.type == "regional") == (var.region != null)
    error_message = "region must be set exactly when type = regional (a null region would silently inherit the provider default)."
  }
}

variable "parent" {
  description = "hierarchical only: organizations/<n>, folders/<n>, or bare digits (treated as a folder id — normalized in the module)."
  type        = string
  default     = null

  validation {
    condition     = var.parent == null || can(regex("^([0-9]+|(organizations|folders)/[0-9]+)$", coalesce(var.parent, "0")))
    error_message = "parent must be organizations/<n>, folders/<n>, or bare digits (folder id)."
  }
}

variable "associate_parent" {
  description = "hierarchical only (module opinion): attach the policy to its parent container."
  type        = bool
  default     = true
}

variable "associations" {
  description = "hierarchical only: extra org/folder attachment targets keyed by token."
  type        = map(string)
  default     = {}
  nullable    = false
}

variable "rules" {
  description = "Policy rules keyed by priority (string) — priority is the rule identity (a GCP limitation: patchRule addresses rules by priority; no identifying name). security_profile_group = SPG ID resolved by the caller from fwp_ngfw (the reference enforces GCP's SPG-before-rule ordering)."
  type = map(object({
    priority                        = number
    description                     = optional(string)
    direction                       = optional(string, "INGRESS")
    action                          = string
    source_ranges                   = optional(list(string), [])
    destination_ranges              = optional(list(string), [])
    source_address_groups           = optional(list(string), [])
    destination_address_groups      = optional(list(string), [])
    source_fqdns                    = optional(list(string), [])
    destination_fqdns               = optional(list(string), [])
    source_region_codes             = optional(list(string), [])
    destination_region_codes        = optional(list(string), [])
    source_threat_intelligence      = optional(list(string), [])
    destination_threat_intelligence = optional(list(string), [])
    source_network_context          = optional(string)
    destination_network_context     = optional(string)
    source_networks                 = optional(list(string), [])
    source_secure_tags              = optional(list(string), [])
    target_secure_tags              = optional(list(string), [])
    target_service_accounts         = optional(list(string), [])
    target_networks                 = optional(list(string), [])
    tls_inspect                     = optional(bool, false)
    security_profile_group          = optional(string)
    layer4 = optional(list(object({
      protocol = string
      ports    = optional(list(string), [])
    })), [{ protocol = "all", ports = [] }])
    logging = optional(bool, false)
    enabled = optional(bool, true) # false = rule INERT (wire: disabled)
  }))
  default  = {}
  nullable = false

  validation {
    condition     = alltrue([for r in var.rules : contains(["allow", "deny", "goto_next", "apply_security_profile_group"], r.action)])
    error_message = "rule action must be allow, deny, goto_next, or apply_security_profile_group."
  }

  validation {
    condition     = alltrue([for r in var.rules : (r.action == "apply_security_profile_group") == (r.security_profile_group != null)])
    error_message = "security_profile_group must be set exactly when action = apply_security_profile_group. A null here on an apply_security_profile_group rule usually means the caller could not resolve the SPG NAME the rule referenced — check it against the rendered names from the ngfw block (spg-<function>-<code>-gbl0)."
  }

  validation {
    condition     = var.type != "regional" || alltrue([for r in var.rules : r.action != "apply_security_profile_group" && !r.tls_inspect])
    error_message = "GCP delta: REGIONAL network firewall policies do not support firewall-endpoint inspection — apply_security_profile_group / tls_inspect are only valid on global and hierarchical policies."
  }

  validation {
    condition     = alltrue([for r in var.rules : r.action != "goto_next" || !r.logging])
    error_message = "logging is not allowed on goto_next rules (provider/API constraint)."
  }

  validation {
    condition     = var.type == "hierarchical" || alltrue([for r in var.rules : length(r.target_networks) == 0])
    error_message = "target_networks (target_resources) is HIERARCHICAL-only."
  }


  validation {
    condition = alltrue([
      for r in var.rules : r.direction == "EGRESS" ? (
        length(concat(r.destination_ranges, r.destination_address_groups, r.destination_fqdns, r.destination_region_codes, r.destination_threat_intelligence)) > 0 || r.destination_network_context != null
        ) : (
        length(concat(r.source_ranges, r.source_address_groups, r.source_fqdns, r.source_region_codes, r.source_threat_intelligence)) > 0 || r.source_network_context != null || length(r.source_secure_tags) > 0
      )
    ])
    error_message = "API constraint: INGRESS rules need >=1 SOURCE matcher and EGRESS rules >=1 DESTINATION matcher (layer4 alone is not a match)."
  }

  validation {
    condition = alltrue([
      for r in var.rules : r.source_network_context == null || length(concat(r.source_ranges, r.source_address_groups, r.source_fqdns, r.source_region_codes, r.source_threat_intelligence)) > 0
      ]) && alltrue([
      for r in var.rules : r.destination_network_context == null || length(concat(r.destination_ranges, r.destination_address_groups, r.destination_fqdns, r.destination_region_codes, r.destination_threat_intelligence)) > 0
    ])
    error_message = "API constraint: network context alone is not a match — a rule with source/destination_network_context needs at least one companion matcher on the same side (ranges/address groups/fqdns/geo/threat-intel; source_networks and target_service_accounts do NOT count)."
  }

  validation {
    condition = alltrue([
      for r in var.rules : alltrue([
        for ref in concat(r.source_address_groups, r.destination_address_groups) :
        var.type == "hierarchical" ? can(regex("^organizations/", ref)) : can(regex("^projects/", ref))
      ])
    ])
    error_message = "API pairing: HIERARCHICAL rules only accept ORGANIZATION-parented address groups; global/regional network policy rules only PROJECT-parented ones (regional additionally requires the group in the policy's own region)."
  }


  validation {
    # live-harvest class: GCP rejects v4+v6 mixed within one rule's ranges
    condition = alltrue([
      for r in var.rules : (
        length([for x in concat(r.source_ranges, r.destination_ranges) : x if can(regex(":", x))]) == 0 ||
        length([for x in concat(r.source_ranges, r.destination_ranges) : x if can(regex(":", x))]) == length(concat(r.source_ranges, r.destination_ranges))
      )
    ])
    error_message = "A rule's ranges are single-family: all IPv4 or all IPv6 - never mixed (GCP rejects the rule)."
  }
}
